export const FETCH_CITY_DATA = 'FETCH_CITY_DATA';
export const CHANGE_SELECTED_DAY = 'CHANGE_SELECTED_DAY';
export const CHANGE_TEMP_SCALE = 'CHANGE_TEMP_SCALE';
export const SHOW_DRAWER = 'SHOW_DRAWER';